language: python

env:
  global:
    - PYPIUSER=grzanka
    #  pypi secured password (PYPIPASS variable), you need to update it to your own if you want to use it
    - secure: "1baYrBIzglZfCjui6gjjjBQ7WsKhKfu/UUmNmGLgHw+K4Y/9JjkYvROEPd/V4TKOxdOS+krmJNlakQk52YsQA6drDGGRRQMJXyGTtrSYj4TSl2pooUEFiX/Il3RZ4EVR94LWVlyUGIIs0UJ+w1WOriU8Ty4nqfdhiSrY9g58EXJR70m/p/2JeMEftQ/xpkLMfGzOSnlLzYbyKzvMAAGqMC1vOWSrVnKcU8zyB5lxnr1sa9Dds12Iq+mJwrQyWGQs/xRiujVU1V2/8KkQuv2ykhkXjV18D45xxuhF9gwkWnapJ9VSFKBnFxfKQjSkESY1YD1Ykv36gIK29AwxiOUG/Iw7sAlh9inV7OwBARcIPSXkuL4SN9CScU92az8qw+fqObQ9JeBIqwOXrLpGQfsEKHJoThPaHVR+eMFcoJo+XGnCvhzCFSb/ZJXM098t+T+p2H/i87iGHn6SIr2MWa8DryWA7Me2EX88LUkYW8xatbySjexldZDXVY9PI3I/+dtWD2P+QpqURsmLaPuHF+jHqaRMaC8LAkTEp8nWQhvHcJrGLI8ixKG4tuD5z8Csf2sPzfYVj86RkD3n2BZPtHknOMo7yt3GwQvQhWmHfqhBhjpzerHemMb8vbiuXaj1VhrvQOa07FNtyJRP9R5tjs7Xkc5QluPZwQLS4ldIMbLtQRs="

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.2
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0" STVER="<30.0.0"
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=coverage
        - python: 3.5-dev
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6-dev
          env: TOXENV=py36
        - python: nightly
          env: TOXENV=py37
        - python: 3.5
          env: TOXENV=docs
        - python: 2.7
          env: TOXENV=pep8
        - python: 3.4
          env: TOXENV=pep8
        - python: 3.5
          env: TOXENV=packaging
#    uncomment and adjust if you want to allow some failures
    allow_failures:
        - python: nightly
          env: TOXENV=py37

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
dist: trusty

# we will use faster container infrastructure
sudo: false


install:
  - travis_wait ./.travis/install_linux.sh

# if scipy is used, then installation from pip last longer than 10min, thus we add travis_wait
script:
  - travis_wait tox --notest && tox
# in case all previous commands in script section succeeded, run deploy (if tag is present)
  - if [[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ $TRAVIS_TAG != "" ]] && [[ $TOXENV == "packaging" ]]; then .travis/deploy_package.sh pypi ; fi
