language: python

cache:
  directories:
  - ~/.cache/pip
  - ~/.pyenv

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.2
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0" STVER="<30.0.0"
        - os: linux
          python: 3.3
          env: TOXENV=py33
        - os: linux
          python: 3.4
          env: TOXENV=py34
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.5
          env: TOXENV=coverage
        - os: linux
          python: 3.5-dev
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.6-dev
          env: TOXENV=py36
        - os: linux
          python: nightly
          env: TOXENV=py37
        - os: linux
          python: 3.4
          env: TOXENV=docs
        - os: linux
          python: 2.7
          env: TOXENV=pep8
        - os: linux
          python: 3.4
          env: TOXENV=pep8
        - os: linux
          python: 3.4
          env:
            - TOXENV=packaging
            - PYPIUSER=grzanka
            #  pypi secured password (PYPIPASS variable)
            - secure: "1baYrBIzglZfCjui6gjjjBQ7WsKhKfu/UUmNmGLgHw+K4Y/9JjkYvROEPd/V4TKOxdOS+krmJNlakQk52YsQA6drDGGRRQMJXyGTtrSYj4TSl2pooUEFiX/Il3RZ4EVR94LWVlyUGIIs0UJ+w1WOriU8Ty4nqfdhiSrY9g58EXJR70m/p/2JeMEftQ/xpkLMfGzOSnlLzYbyKzvMAAGqMC1vOWSrVnKcU8zyB5lxnr1sa9Dds12Iq+mJwrQyWGQs/xRiujVU1V2/8KkQuv2ykhkXjV18D45xxuhF9gwkWnapJ9VSFKBnFxfKQjSkESY1YD1Ykv36gIK29AwxiOUG/Iw7sAlh9inV7OwBARcIPSXkuL4SN9CScU92az8qw+fqObQ9JeBIqwOXrLpGQfsEKHJoThPaHVR+eMFcoJo+XGnCvhzCFSb/ZJXM098t+T+p2H/i87iGHn6SIr2MWa8DryWA7Me2EX88LUkYW8xatbySjexldZDXVY9PI3I/+dtWD2P+QpqURsmLaPuHF+jHqaRMaC8LAkTEp8nWQhvHcJrGLI8ixKG4tuD5z8Csf2sPzfYVj86RkD3n2BZPtHknOMo7yt3GwQvQhWmHfqhBhjpzerHemMb8vbiuXaj1VhrvQOa07FNtyJRP9R5tjs7Xkc5QluPZwQLS4ldIMbLtQRs="
            #  Code Climate secured token (CODECLIMATE_REPO_TOKEN variable)
            - secure: "UzByLKDLbYN9kU7UvIt/CmyHTBMVqMMR0XSj9J4KyXdW0wtFZU+ZG7pm5SoMcW/S/b2KoYINZrYqA7OGad+gc3EYlYfN2Y8+gI2bo9q+tHfxGojim2YqTxHsOS2I41QoxEtQF+5SW2p1HKj/tHz4x/U/lNGHRtdhcDmB8W3gWAnRnGXztk96hmdJzVxx5aY3/2x/p3Psgl2PI+DIpmhvi1EqKrN5+YLiNlGoNVesfbZL0os9iNwKWoo0xFqsIntUvfw1SFYTFQhorUxVtF8iVJKsWaFS4P7BJ8QSTcwG+WgNG2faBOfEcUoM5OIIIHN0rYRodL2DNgx5u+JWbBIP97hwMtets58c+3vKKHsoobxgwa6xSYdQHibkbcZn/LuifzmmyLpqFqWqQt8v83VLb6+cgOPqFAaHJlNs9eHTTaEJ7NSfB9U4XdEaCX1KfZBbCIj/3Kz5KlPp+Lt7TIDCD7DbKI1fStoy5VSBarj32ZRztIX/D5vNj4DgTMKfJfZV5bIdwXdoMgISIR+l/RlGWfcteXVb6/w2HC+m3eZWHdPpLeuHvlA/4VxXmAwpum2MOUcrZYNnuQPFGDEdh8KLQ4WExtLH7RySxO64UI59hEqOeTSM1A2/SaLwi/AxhUOAxw5DinimIm7zEn8ZjxoCz0mkg9TLOZ6gh2Frt1yCro4="
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0" STVER="<30.0.0"
        - os: osx
          language: generic
          env: TOXENV=py27
#    uncomment and adjust if you want to allow some failures
    allow_failures:
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.6-dev
          env: TOXENV=py36
        - os: linux
          python: nightly
          env: TOXENV=py37

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
sudo: required
dist: trusty

before_install:
  - PYTHON_VERSION="py3"
  - if [[ $TOXENV == "py27" ]]; then PYTHON_VERSION="py2" ; fi
  - sudo bash ./install_deps.sh $PYTHON_VERSION

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then travis_wait bash ./.travis/install_linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then travis_wait 60 bash ./.travis/install_osx.sh ; fi

# if scipy is used, then installation from pip last longer than 10min, thus we add travis_wait
script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then travis_wait tox --notest && tox -- -n 8 ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then travis_wait bash ./.travis/run_osx.sh ; fi

after_success:
  # send coverage data
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_OS_NAME == "linux" ]] && [[ $TOXENV == "packaging" ]]; then bash .travis/send_coverage.sh ; fi
  # deploy to normal pypi server if tag is present
  - if [[ $TRAVIS_TAG != "" ]] && [[ $TOXENV == "packaging" ]]; then bash .travis/deploy_package.sh pypi ; fi

notifications:
  email:
    - grzanka@agh.edu.pl
