language: python
python:
    - "3.4"

install:
    - sudo apt-get install gfortran libopenblas-dev liblapack-dev
    - pip install -r requirements.txt
    - cd beprof
    - python setup.py install

script: python unittests.py
