# based on https://github.com/audreyr/cookiecutter/blob/master/appveyor.yml

# validation page for appveyor config: https://ci.appveyor.com/tools/validate-yaml

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python27-x64"
      TOX_ENV: "py27"

#  temporarily disabled as Appveyor seems to have broken config of Python 3.3
#    - PYTHON: "C:\\Python33"
#      TOX_ENV: "py33"
#
#    - PYTHON: "C:\\Python33-x64"
#      TOX_ENV: "py33"

    - PYTHON: "C:\\Python34"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python34-x64"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python35-x64"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python34-x64"
      TOX_ENV: "docs"

    - PYTHON: "C:\\Python34-x64"
      TOX_ENV: "packaging"

    - PYTHON: "C:\\Python27-x64"
      TOX_ENV: "py3pep8"

    - PYTHON: "C:\\Python34-x64"
      TOX_ENV: "pep8"

# until we fix code of example project, lets allow failure here
#matrix:
#  allow_failures:
#      - TOX_ENV: "py27"
#      - TOX_ENV: "py33"


init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"

build: false

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"