# based on https://github.com/audreyr/cookiecutter/blob/master/appveyor.yml

# validation page for appveyor config: https://ci.appveyor.com/tools/validate-yaml

environment:
  matrix:
    - platform: x86
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"

    - platform: x64
      PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"


# until we fix code of example project, lets allow failure here
#matrix:
#  allow_failures:
#      - TOX_ENV: "py27"
#      - TOX_ENV: "py33"


init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - python -V
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - set PATH=C:\Miniconda\Scripts
  - ps: If ($env:Platform -Match "x64") {$env:PATH="C:\Miniconda-x64\Scripts"}
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

# create and activate Conda virtualenv
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION%
  - activate python%PYTHON_VERSION%
  - python -V

# install dependencies
  - conda install -q --name python%PYTHON_VERSION% setuptools wheel numpy scipy
  - pip install -r tests/requirements-test.txt
  - pip install -r requirements.txt

before_test:
  - python -c "import numpy as np;print(np.version.version)"
  - python -c "import scipy as sp;print(sp.version.version)"
  - python c:\miniconda\envs\python%PYTHON_VERSION%\scripts\versioneer install

build: false

test_script:
  - py.test